{
    "list": [{
        "seq": "00",
        "type": "intxt",
        "title": "하기스몰",
        "notice":"",
        "pop_tit": "하기스몰",
        "pop_notice":"하기스몰 사이트 제작",
        "client":"유한킴벌리",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2011.10",
        "size":"220,260",
        "backgroundColor":"#ab0000",
        "link":""
    }, {
        "seq": "01",
        "type": "intxt",
        "title": "SKC",
        "notice":"",
        "pop_tit": "SKC OFFICIAL SITE",
        "pop_notice":"SKC OFFICIAL 사이트 제작",
        "client":"SKC",
        "category": "all, website",
        "category_tit": "website",
        "period": "2011.04",
        "size":"220,220",
        "backgroundColor":"#f8841d",
        "link":""
    }, {
        "seq": "02",
        "type": "outtxt",
        "title": "SAMSUNG CARD WEBZINE 2011",
        "notice":"",
        "pop_tit": "SAMSUNG CARD WEBZINE 2011",
        "pop_notice":"SAMSUNG CARD WEBZINE 2011 제작",
        "client":"삼성카드",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2011",
        "size":"220,320",
        "backgroundColor":"#347ebd",
        "link":""
    }, {
        "seq": "03",
        "type": "outtxt",
        "title": "KB CARD WEBZINE 2011",
        "notice":"",
        "pop_tit": "KB CARD WEBZINE 2011",
        "pop_notice":"KB CARD WEBZINE 2011 제작",
        "client":"KB카드",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2011",
        "size":"220,340",
        "backgroundColor":"#ffd440",
        "link":""
    }, {
        "seq": "04",
        "type": "intxt",
        "title": "17茶",
        "title_color":"white",
        "notice":"",
        "notice_color":"white",
        "pop_tit": "17茶",
        "pop_notice":"17茶 management/promotion 제작",
        "client":"남양유업",
        "category": "all, website, management/promotion",
        "category_tit": "website, management/promotion",
        "period": "2010",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#f28f29",
        "link":""
    }, {
        "seq": "05",
        "type": "outtxt",
        "title": "SK건설",
        "notice":"",
        "pop_tit": "SK건설 SITE",
        "pop_notice":"SK건설 SITE 사이트 제작",
        "client":"SK",
        "category": "all, website",
        "category_tit": "website",
        "period": "2012.04",
        "size":"220,380",
        "backgroundColor":"#c7cdce",
        "link":""
    }, {
        "seq": "06",
        "type": "outtxt",
        "title": "식품안전정보원",
        "notice":"",
        "pop_tit": "식품안전정보원",
        "pop_notice":"식품안전정보원 사이트 제작",
        "client":"식품안전정보원",
        "category": "all, website",
        "category_tit": "website",
        "period": "2012.07",
        "size":"220,300",
        "backgroundColor":"#c7cdce",
        "link":""
    }, {
        "seq": "07",
        "type": "intxt",
        "title": "SK PCMS",
        "notice":"",
        "pop_tit": "SK PCMS",
        "pop_notice":"SK PCMS 사이트 제작",
        "client":"SK",
        "category": "all, website",
        "category_tit": "website",
        "period": "2012.07",
        "size":"220,220",
        "backgroundColor":"#e41b00",
        "link":""
    }, {
        "seq": "08",
        "type": "intxt",
        "title": "SK코원에너지서비스",
        "notice":"",
        "pop_tit": "SK코원에너지서비스 SITE",
        "pop_notice":"SK코원에너지서비스 SITE 사이트 제작",
        "client":"SK",
        "category": "all, website",
        "category_tit": "website",
        "period": "2012.07",
        "size":"220,220",
        "backgroundColor":"#f7851d",
        "link":""
    }, {
        "seq": "09",
        "type": "boxouttxt",
        "title": "SBS 대선 사이트 구축",
        "notice":"SBS가 2012년 18대 대선을 위한 사이트를 제작하였습니다.",
        "pop_tit": "SBS 대선(웹접근성 준수)",
        "pop_notice":"SBS 대선 사이트 제작",
        "client":"SBS",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2012.12",
        "size":"460,420",
        "backgroundColor":"#c7cdce",
        "link":""
    }, {
        "seq": "10",
        "type": "boxouttxt",
        "title": "SAMSUNG CARD WEBZINE 2012",
        "notice":"SAMSUNG CARD WEBZINE을 제작하였습니다.",
        "pop_tit": "SAMSUNG CARD WEBZINE 2012",
        "pop_notice":"SAMSUNG CARD WEBZINE 2012 제작",
        "client":"삼성카드",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2012",
        "size":"460,380",
        "backgroundColor":"#347ebd",
        "link":""
    }, {
        "seq": "11",
        "type": "boxouttxt",
        "title": "KB CARD WEBZINE 2012",
        "notice":"KB CARD WEBZINE을 제작하였습니다.",
        "pop_tit": "KB CARD WEBZINE 2012",
        "pop_notice":"KB CARD WEBZINE 2012 제작",
        "client":"KB카드",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2012",
        "size":"460,340",
        "backgroundColor":"#ffd440",
        "link":""
    }, {
        "seq": "12",
        "type": "intxt",
        "title": "하기스몰",
        "notice":"2012 연간 계약 운영",
        "pop_tit": "2012 하기스몰 연간 계약 운영",
        "pop_notice":"2012 하기스몰 연간 계약",
        "client":"하기스",
        "category": "all, website",
        "category_tit": "website",
        "period": "2012",
        "size":"220,260",
        "backgroundColor":"#ab0000",
        "link":""
    }, {
        "seq": "13",
        "type": "intxt",
        "title": "SK E&S",
        "notice":"",
        "pop_tit": "SK E&S SITE",
        "pop_notice":"SK E&S SITE 사이트 제작",
        "client":"SK E&S",
        "category": "all, website",
        "category_tit": "website",
        "period": "2012.10",
        "size":"220,220",
        "backgroundColor":"#ff7a01",
        "link":""
    }, {
        "seq": "14",
        "type": "outtxt",
        "title": "SBS 글로벌",
        "notice":"",
        "pop_tit": "SBS Global SITE",
        "pop_notice":"SBS Global SITE 사이트 제작",
        "client":"SBS",
        "category": "all, website",
        "category_tit": "website",
        "period": "2012.11",
        "size":"220,340",
        "backgroundColor":"#c7cdce",
        "link":""
    }, {
        "seq": "15",
        "type": "intxt",
        "title": "SBS SOTY SPECIAL",
        "title_color":"white",
        "notice":"",
        "notice_color":"white",
        "pop_tit": "SBS SOTY SPECIAL",
        "pop_notice":"SBS SOTY SPECIAL 사이트 제작",
        "client":"SBS",
        "category": "all, website",
        "category_tit": "website",
        "period": "2013.11",
        "period_color":"white",
        "size":"220,220",
        "backgroundColor":"#c7cdce",
        "link":""
    }, {
        "seq": "16",
        "type": "boxintxt",
        "title": "하기스몰 사이트 리뉴얼",
        "notice":"하기스몰 오픈마켓을 제작하여 장애니 차별금지법 인증마크를 획득하였습니다.",
        "pop_tit": "하기스몰(웹접근성 인증)",
        "pop_notice":"하기스몰 사이트 제작 웹접근성 인증",
        "client":"유한킴벌리",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2013.07",
        "size":"460,470",
        "backgroundColor":"#ab0000",
        "link":""
    }, {
        "seq": "17",
        "type": "intxt",
        "title": "굿나이트",
        "notice":"",
        "pop_tit": "굿나이트(웹접근성 인증)",
        "pop_notice":"굿나이트 사이트 제작 웹 접근성 인증",
        "client":"유한킴벌리",
        "category": "all, website",
        "category_tit": "website",
        "period": "2013.07",
        "size":"220,220",
        "backgroundColor":"#c7cdce",
        "link":""
    }, {
        "seq": "18",
        "type": "outtxt",
        "title": "더블하트",
        "notice":"",
        "pop_tit": "더블하트(웹접근성 인증)",
        "pop_notice":"더블하트 사이트 제작 웹접근성 인증",
        "client":"유한킴벌리",
        "category": "all, website",
        "category_tit": "website",
        "period": "2013.07",
        "size":"220,300",
        "backgroundColor":"#ffcec2",
        "link":""
    }, {
        "seq": "19",
        "type": "outtxt",
        "title": "그린핑거",
        "notice":"",
        "pop_tit": "그린핑거(웹접근성 인증)",
        "pop_notice":"그린핑거 사이트 제작 웹접근성 인증",
        "client":"유한킴벌리",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2013.07",
        "size":"220,300",
        "backgroundColor":"#576d3f",
        "link":""
    }, {
        "seq": "20",
        "type": "intxt",
        "title": "하기스 선물대잔치",
        "notice":"",
        "pop_tit": "하기스 선물대잔치",
        "pop_notice":"하기스 선물대잔치 사이트 제작 웹접근성 인증",
        "client":"유한킴벌리",
        "category": "all, website",
        "category_tit": "website",
        "period": "2013.07",
        "size":"220,220",
        "backgroundColor":"#ab0000",
        "link":""
    }, {
        "seq": "21",
        "type": "intxt",
        "title": "하기스몰 어플",
        "title_color":"white",
        "notice":"",
        "notice_color":"white",
        "pop_tit": "하기스몰",
        "pop_notice":"하기스몰 어플리케이션 제작",
        "client":"하기스몰",
        "category": "all, application",
        "category_tit": "application",
        "period": "2013",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#ab0000",
        "link":""
    }, {
        "seq": "22",
        "type": "intxt",
        "title": "하기스몰",
        "notice":"2013년 연간계약 운영",
        "pop_tit": "2013 하기스몰 연간 계약 운영",
        "pop_notice":"2013 하기스몰 연간 계약 운영",
        "client":"하기스",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2013",
        "size":"220,260",
        "backgroundColor":"#ab0000",
        "link":""
    }, {
        "seq": "23",
        "type": "intxt",
        "title": "하기스 라운지웨어",
        "notice":"",
        "pop_tit": "하기스 라운지웨어(웹접근성 인증)",
        "pop_notice":"하기스 라운지웨어 사이트 제작 웹 접근성 인증",
        "client":"유한킴벌리",
        "category": "all, website",
        "category_tit": "website",
        "period": "2013.07",
        "size":"220,220",
        "backgroundColor":"#fdd0d2",
        "link":""
    }, {
        "seq": "24",
        "type": "intxt",
        "title": "순수한그루",
        "notice":"",
        "pop_tit": "순수한그루",
        "pop_notice":"순수한그루 사이트 제작 웹접근성 인증",
        "client":"유한킴벌리",
        "category": "all, website",
        "category_tit": "website",
        "period": "2013.07",
        "size":"220,220",
        "backgroundColor":"#dbb67f",
        "link":""
    }, {
        "seq": "25",
        "type": "boxintxt",
        "title": "팬틴 브랜드 사이트 구축",
        "notice":"팬틴은 P&G의 대표 헤어 브랜드 라인으로 역동적인 모션을 스크립트로 구사하였으며, 웹 인증 마크로 획득하였습니다.",
        "pop_tit": "팬틴 브랜드 사이트 구축",
        "pop_notice":"팬틴은 P&G의 대표 헤어 브랜드 라인으로 역동적인 모션을 스크립트로 구사하였으며, 웹 인증 마크도 획득하였습니다.",
        "client":"팬틴",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2015.08",
        "size":"460,495",
        "backgroundColor":"#ecca66",
        "link":""
    }, {
        "seq": "26",
        "type": "outtxt",
        "title": "참존그룹",
        "notice":"",
        "pop_tit": "참존그룹",
        "pop_notice":"참존그룹사 사이트 제작",
        "client":"참존",
        "category": "all, website",
        "category_tit": "website",
        "period": "2014.10",
        "size":"220,300",
        "backgroundColor":"#152b74",
        "link":""
    }, {
        "seq": "27",
        "type": "boxouttxt",
        "title": "참존화장품",
        "notice":"창립 30주년을 맞는 화장품계의 큰 형님 참존화장품의 대표 사이트 입니다.",
        "pop_tit": "참존화장품",
        "pop_notice":"참존 화장품 사이트 제작",
        "client":"참존",
        "category": "all, website, mobile, shopping mall",
        "category_tit": "website, mobile, shopping mall",
        "period": "2014.09",
        "size":"460,400",
        "backgroundColor":"#152b74",
        "link":""
    }, {
        "seq": "28",
        "type": "outtxt",
        "title": "참존 쇼핑몰 리뉴얼",
        "notice":"",
        "pop_tit": "참존 쇼핑몰",
        "pop_notice":"참존 쇼핑몰 리뉴얼",
        "client":"참존",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2014.05",
        "size":"220,340",
        "backgroundColor":"#152b74",
        "link":""
    }, {
        "seq": "29",
        "type": "intxt",
        "title": "참존화장품",
        "title_color":"white",
        "notice":"2014년 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "2014년 참존 연간 계약 운영",
        "pop_notice":"2014년 참존 연간 계약 운영",
        "client":"참존",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2014",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#152b74",
        "link":""
    }, {
        "seq": "30",
        "type": "intxt",
        "title": "참존 쇼핑몰",
        "title_color":"white",
        "notice":"2014년 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "2014 참존 쇼핑몰 연간 계약 운영",
        "pop_notice":"2014 참존 쇼핑몰 연간 계약 운영",
        "client":"참존",
        "category": "all, management/promotion, mobile",
        "category_tit": "management/promotion, mobile",
        "period": "2014",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#152b74",
        "link":""
    }, {
        "seq": "31",
        "type": "intxt",
        "title": "팬틴",
        "notice":"2014년 연간 계약 운영",
        "pop_tit": "2014년 팬틴 연간 계약 운영",
        "pop_notice":"2014년 팬틴 연간 계약 운영",
        "client":"팬틴",
        "category": "all, management/promotion, mobile",
        "category_tit": "management/promotion, mobile",
        "period": "2014",
        "size":"220,340",
        "backgroundColor":"#ecca66",
        "link":""
    }, {
        "seq": "32",
        "type": "intxt",
        "title": "그린핑거",
        "title_color":"white",
        "notice":"2014년 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "2014년 그린핑거 연간 계약 운영",
        "pop_notice":"2014년 그린핑거 연간 계약 운영",
        "client":"그린핑거",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2013.07",
        "period_color":"white",
        "size":"220,220",
        "backgroundColor":"#576d3f",
        "link":""
    }, {
        "seq": "33",
        "type": "intxt",
        "title": "더블하트",
        "notice":"2014년 연간 계약 운영",
        "pop_tit": "2014년 더블하트 연간 계약 운영",
        "pop_notice":"2014년 더블하트 연간 계약 운영",
        "client":"더블하트",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2014",
        "size":"220,220",
        "backgroundColor":"#ffcdc2",
        "link":""
    }, {
        "seq": "34",
        "type": "intxt",
        "title": "하기스몰",
        "notice":"2014년 연간 계약 운영",
        "pop_tit": "2014 하기스몰 연간 계약 운영",
        "pop_notice":"2014 하기스몰 연간 계약 운영",
        "client":"하기스",
        "category": "all, management/promotion, shopping mall",
        "category_tit": "management/promotion, shopping mall",
        "period": "2014",
        "size":"220,260",
        "backgroundColor":"#ab0000",
        "link":""
    }, {
        "seq": "35",
        "type": "outtxt",
        "title": "SKC MCNS",
        "notice":"",
        "pop_tit": "SKC MCNS",
        "pop_notice":"SKC MCNS",
        "client":"SKC MCNS",
        "category": "all, website",
        "category_tit": "website",
        "period": "2015.12",
        "size":"220,340",
        "backgroundColor":"#6faa2c",
        "link":""
    }, {
        "seq": "36",
        "type": "outtxt",
        "title": "SK인포섹",
        "notice":"",
        "pop_tit": "SK인포섹",
        "pop_notice":"SK인포섹 사이트 제작 웹접근성 인증",
        "client":"SK인포섹",
        "category": "all, website",
        "category_tit": "website",
        "period": "2015.12",
        "size":"220,300",
        "backgroundColor":"#c7cdce",
        "link":""
    }, {
        "seq": "37",
        "type": "boxouttxt",
        "title": "SK 바이오랜드",
        "notice":"SK가 국내 1위 화장품 원료 기업인 바이오랜드를 인수하여 전문적인 바이오랜드와 SK의 브랜드 가치를 높이고 바이오랜드만의 친환경적인 느낌으로 리뉴얼하였습니다.",
        "pop_tit": "SK 바이오랜드",
        "pop_notice":"SK가 국내 1위 화장품 원료 기업인 바이오랜드를 인수하여 전문적인 바이오랜드와 SK의 브랜드 가치를 높이고 바이오랜드만의 친환경적인 느낌으로 리뉴얼하였습니다.",
        "client":"SK 바이오랜드",
        "category": "all, website",
        "category_tit": "website",
        "period": "2015.12",
        "size":"460,340",
        "backgroundColor":"#009c43",
        "link":""
    }, {
        "seq": "38",
        "type": "boxouttxt",
        "title": "클라리틴",
        "notice":"바이엘 코리아의 클라리틴 약품에 대한 소개 사이트로 PC, Mobile, 프로모션이 같이 제작되었습니다.",
        "pop_tit": "바이엘코리아 (클라리틴)",
        "pop_notice":"바이엘 코리아의 클라리틴 약품에 대한 소개 사이트로 PC, Mobile, 프로모션이 같이 제작되었습니다.",
        "client":"바이엘코리아",
        "category": "all, website, mobile, management/promotion",
        "category_tit": "website, mobile, management/promotion",
        "period": "2015.08",
        "size":"460,320",
        "backgroundColor":"#0172be",
        "link":""
    }, {
        "seq": "39",
        "type": "boxouttxt",
        "title": "대한통운 화물정보망",
        "notice":"CJ 대한통운의 화물정보망 운영관리 시스템 사이트로 화물조회와 공차 정보, 가맹점 운영지원 시스템을 지원하는 사이트입니다.",
        "pop_tit": "대한통운 화물정보망",
        "pop_notice":"CJ 대한통운의 화물정보망 운영관리 시스템 사이트로 화물조회와 공차 정보, 가맹점 운영지원 시스템을 지원하는 사이트입니다.",
        "client":"CJ 대한통운",
        "category": "all, website",
        "category_tit": "website",
        "period": "2015",
        "size":"460,400",
        "backgroundColor":"#5d5c61",
        "link":""
    }, {
        "seq": "40",
        "type": "intxt",
        "title": "오피스탁 주식정보",
        "title_color":"white",
        "notice":"",
        "notice_color":"white",
        "pop_tit": "오피스탁 주식정보",
        "pop_notice":"오피스탁 주식정보 어플리케이션 제작",
        "client":"오피스탁",
        "category": "all, application",
        "category_tit": "application",
        "period": "2015.08",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#4f4f4f",
        "link":""
    }, {
        "seq": "41",
        "type": "outtxt",
        "title": "SKC",
        "notice":"",
        "pop_tit": "SKC",
        "pop_notice":"SKC 사이트 제작 웹접근성 인증",
        "client":"SKC",
        "category": "all, website",
        "category_tit": "website",
        "period": "2015.05",
        "size":"220,310",
        "backgroundColor":"#c7cdce",
        "link":""
    }, {
        "seq": "42",
        "type": "outtxt",
        "title": "SKC 윈도우필름",
        "notice":"",
        "pop_tit": "SKC 윈도우필름",
        "pop_notice":"SKC윈도우필름 사이트 제작 웹접근성 인증",
        "client":"SKC",
        "category": "all, web accessibility",
        "category_tit": "web accessibility",
        "period": "2015.05",
        "size":"220,300",
        "backgroundColor":"#c7cccf",
        "link":""
    }, {
        "seq": "43",
        "type": "boxintxt",
        "title": "참존 참인셀 브랜드 사이트 구축",
        "notice":"참존 화장품의 대표 브랜드 중 하나인 참인셀 사이트로 패럴럭스 기반의 사이트를 제작하였습니다.",
        "pop_tit": "참존 참인셀 브랜드",
        "pop_notice":"참존 참인셀 브랜드 사이트 제작",
        "client":"참존",
        "category": "all, website, mobile, management/promotion",
        "category_tit": "website, mobile, management/promotion",
        "period": "2015.08",
        "size":"460,420",
        "backgroundColor":"#c5b690",
        "link":""
    }, {
        "seq": "44",
        "type": "intxt",
        "title": "참존 화장품",
        "title_color":"white",
        "notice":"2015년 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "2015년 참존 연간 계약 운영",
        "pop_notice":"2015년 참존 연간 계약 운영",
        "client":"참존",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2015",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#152b74",
        "link":""
    }, {
        "seq": "45",
        "type": "intxt",
        "title": "참존 쇼핑몰",
        "title_color":"white",
        "notice":"2015년 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "2015년 참존 쇼핑몰 연간 계약 운영",
        "pop_notice":"2015년 참존 쇼핑몰 연간 계약 운영",
        "client":"참존",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2015",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#152b74",
        "link":""
    }, {
        "seq": "46",
        "type": "intxt",
        "title": "맥도날드",
        "title_color":"white",
        "notice":"2015년 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "2015년 맥도날드 연간 계약 운영",
        "pop_notice":"2015년 맥도날드 연간 계약 운영",
        "client":"맥도날드",
        "category": "all, management/promotion, mobile, shopping mall",
        "category_tit": "management/promotion, mobile, shopping mall",
        "period": "2015",
        "period_color":"white",
        "size":"220,340",
        "backgroundColor":"#b70707",
        "link":""
    }, {
        "seq": "47",
        "type": "intxt",
        "title": "그린핑거",
        "title_color":"white",
        "notice":"2015년 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "2015년 그린핑거 연간 계약 운영",
        "pop_notice":"2015년 그린핑거 연간 계약 운영",
        "client":"유한킴벌리",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2015",
        "period_color":"white",
        "size":"220,220",
        "backgroundColor":"#576d3f",
        "link":""
    }, {
        "seq": "48",
        "type": "intxt",
        "title": "더블하트",
        "notice":"2015년 연간 계약 운영",
        "pop_tit": "2015년 더블하트 연간 계약 운영",
        "pop_notice":"2015년 더블하트 연간 계약 운영",
        "client":"더블하트",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2015",
        "size":"220,220",
        "backgroundColor":"#ffcec2",
        "link":""
    }, {
        "seq": "49",
        "type": "outtxt",
        "title": "맥도날드 주문 어플리케이션",
        "notice":"",
        "pop_tit": "맥도날드 주문 어플리케이션",
        "pop_notice":"맥도날드 주문 어플리케이션 제작",
        "client":"맥도날드",
        "category": "all, application, shopping mall",
        "category_tit": "application, shopping mall",
        "period": "2015",
        "size":"220,400",
        "backgroundColor":"#b70707",
        "link":""
    }, {
        "seq": "50",
        "type": "intxt",
        "title": "팬틴",
        "notice":"2015년 연간 계약 운영",
        "pop_tit": "2015년 팬틴 연간 계약 운영",
        "pop_notice":"2015년 팬틴 연간 계약 운영",
        "client":"P&G",
        "category": "all, management/promotion, mobile",
        "category_tit": "management/promotion, mobile",
        "period": "2015",
        "size":"220,340",
        "backgroundColor":"#ecca66",
        "link":""
    }, {
        "seq": "51",
        "type": "intxt",
        "title": "맥도날드",
        "title_color":"white",
        "notice":"2016년 맥도날드 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "2016년 맥도날드 연간 계약 운영",
        "pop_notice":"2016년 맥도날드 연간 계약 운영",
        "client":"맥도날드",
        "category": "all, management/promotion, mobile",
        "category_tit": "management/promotion, mobile",
        "period": "2016",
        "period_color":"white",
        "size":"460,240",
        "backgroundColor":"#b70707",
        "link":""
    }, {
        "seq": "52",
        "type": "intxt",
        "title": "premier OB",
        "title_color":"white",
        "notice":"2016년 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "premier OB 2016년 연간 계약 운영",
        "pop_notice":"premier OB 2016년 연간 계약 운영",
        "client":"premier OB",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2016",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#f4bb2c",
        "link":""
    }, {
        "seq": "53",
        "type": "boxintxt",
        "title": "영동군청 국악음원디지털 사업",
        "notice":"영동군에서 옛날의 국악 음원들을 복원하고 쉽게 관리하고자 새롭게 시스템을 구축하였습니다.",
        "pop_tit": "영동군청 국악음원디지털 사업",
        "pop_notice":"영동군에서 옛날의 국악 음원들을 복원하고 쉽게 관리하고자 새롭게 시스템을 구축하였습니다.",
        "client":"영동군청",
        "category": "all, website, management/promotion",
        "category_tit": "website, management/promotion",
        "period": "2015.12",
        "size":"460,420",
        "backgroundColor":"#235eaa",
        "link":""
    }, {
        "seq": "54",
        "type": "intxt",
        "title": "참존쇼핑몰",
        "title_color":"white",
        "notice":"2016년 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "2016년 참존 쇼핑몰 연간 계약 운영",
        "pop_notice":"2016년 참존 쇼핑몰 연간 계약 운영",
        "client":"참존",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2016",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#152b74",
        "link":""
    }, {
        "seq": "55",
        "type": "intxt",
        "title": "참존화장품",
        "title_color":"white",
        "notice":"2016년 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "2016년 참존 연간 계약 운영",
        "pop_notice":"2016년 참존 연간 계약 운영",
        "client":"참존",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2016",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#152b74",
        "link":""
    }, {
        "seq": "56",
        "type": "boxouttxt",
        "title": "르노삼성 SM6 브랜드 사이트 구축",
        "notice":"13th WEB AWARD KOREA에서 르노삼성 SM6 브랜드 사이트가 자동차 분야에서 최우수상을 수상하였습니다.",
        "pop_tit": "르노삼성 SM6 브랜드 사이트 구축",
        "pop_notice":"13th WEB AWARD KOREA에서 르노삼성 SM6 브랜드 사이트가 자동차 분야에서 최우수상을 수상하였습니다.",
        "client":"르노삼성",
        "category": "all, website, mobile, management/promotion",
        "category_tit": "website, mobile, management/promotion",
        "period": "2016.02",
        "size":"460,380",
        "backgroundColor":"#c7cdce",
        "link":""
    }, {
        "seq": "57",
        "type": "outtxt",
        "title": "불가리 B.zero1 반지 이벤트",
        "notice":"",
        "pop_tit": "불가리 B.zero1 반지 이벤트",
        "pop_notice":"불가리 B.zero1 반지 이벤트.",
        "client":"BVLGARI",
        "category": "all, management/promotion, mobile",
        "category_tit": "management/promotion, mobile",
        "period": "2016.10",
        "size":"220,400",
        "backgroundColor":"#d7c690",
        "link":""
    }, {
        "seq": "58",
        "type": "boxintxt",
        "title": "참존 화장품 리뉴얼",
        "notice":"참존 화장품의 브랜드 가치를 높이고 브랜드의 아름다운 느낌이 녹아들도록 새롭게 제작하였습니다.",
        "pop_tit": "참존 화장품 리뉴얼",
        "pop_notice":"참존 화장품의 브랜드 가치를 높이고 브랜드의 아름다운 느낌이 녹아들도록 새롭게 제작하였습니다.",
        "client":"참존 화장품",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2016.11",
        "size":"460,470",
        "backgroundColor":"#152b74",
        "link":""
    }, {
        "seq": "59",
        "type": "boxintxt",
        "title": "올댓옥션 자동차 공매",
        "notice":"모두가 쉽고 빠르게 사용할 수 있는 자동차 종합 유통 플랫폼인 올댓옥션을 위해 심플하고 편리한 ux/ui로 디자인하여 구축하였다.",
        "pop_tit": "올댓옥션 자동차 공매",
        "pop_notice":"모두가 쉽고 빠르게 사용할 수 있는 자동차 종합 유통 플랫폼인 올댓옥션을 위해 심플하고 편리한 ux/ui로 디자인하여 구축하였다.",
        "client":"SK엔카 올댓옥션",
        "category": "all, website, mobile, application, shopping mall",
        "category_tit": "website, mobile, application, shopping mall",
        "period": "2017.01",
        "size":"460,470",
        "backgroundColor":"#0a5587",
        "link":""
    }, {
        "seq": "60",
        "type": "intxt",
        "title": "네스카페 돌체구스토",
        "title_color":"white",
        "notice":"",
        "notice_color":"white",
        "pop_tit": "네스카페 돌체구스토 운영",
        "pop_notice":"",
        "client":"네스카페",
        "category": "all, management/promotion, mobile",
        "category_tit": "management/promotion, mobile",
        "period": "2017.03",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#6a3c2b",
        "link":""
    }, {
        "seq": "61",
        "type": "intxt",
        "title": "트럭킹",
        "title_color":"white",
        "notice":"2017년 연간 계약 운영",
        "notice_color":"white",
        "pop_tit": "트럭킹 운영",
        "pop_notice":"2017년 연간 계약 운영",
        "client":"트럭킹",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2017.01",
        "period_color":"white",
        "size":"220,200",
        "backgroundColor":"#cb2523",
        "link":""
    }, {
        "seq": "62",
        "type": "outtxt",
        "title": "위닉스 프로모션 맑은하늘 맑은 웃음",
        "notice":"",
        "pop_tit": "위닉스 프로모션 맑은하늘 맑은 웃음",
        "pop_notice":"",
        "client":"위닉스",
        "category": "all, management/promotion, mobile",
        "category_tit": "management/promotion, mobile",
        "period": "2017.05",
        "size":"220,300",
        "backgroundColor":"#85c441",
        "link":""
    }, {
        "seq": "63",
        "type": "outtxt",
        "title": "위닉스 프로모션 행복한물 선물하기",
        "notice":"",
        "pop_tit": "위닉스 프로모션 행복한물 선물하기",
        "pop_notice":"참존 화장품의 브랜드 가치를 높이고 브랜드의 아름다운 느낌이 녹아들도록 새롭게 제작하였습니다.",
        "client":"위닉스",
        "category": "all, management/promotion, mobile",
        "category_tit": "management/promotion, mobile",
        "period": "2017.05",
        "size":"220,300",
        "backgroundColor":"#85c441",
        "link":""
    }, {
        "seq": "64",
        "type": "boxintxt",
        "title": "SK 엔카 옥션",
        "notice":"14th WEB AWARD KOREA에서 SK엔카옥션 사이트가 전문정보 분야, 정보서비스 분야에서 최우수상을 수상하였습니다.",
        "pop_tit": "SK 엔카 옥션",
        "pop_notice":"14th WEB AWARD KOREA에서 SK엔카옥션 사이트가 전문정보 분야, 정보서비스 분야에서 최우수상을 수상하였습니다.",
        "client":"SK건설",
        "category": "all, website, mobile, application, shopping mall",
        "category_tit": "website, mobile, application, shopping mall",
        "period": "2017.09",
        "size":"460,400",
        "backgroundColor":"#e51736",
        "link":""
    }, {
        "seq": "65",
        "type": "boxintxt",
        "title": "SK DIGITAL CONSULTING",
        "notice":"새로운 미래를 여는 SK디지털컨설팅의 넓은 분야, 신개념 디지털 컨설팅 서비스를 위해 진취적이고 미래적인 비주얼과 모든 디바이스에 맞는 반응형 ux/ui로 디자인하여 구축하였다.",
        "pop_tit": "SK DIGITAL CONSULTING",
        "pop_notice":"새로운 미래를 여는 SK디지털컨설팅의 넓은 분야, 신개념 디지털 컨설팅 서비스를 위해 진취적이고 미래적인 비주얼과 모든 디바이스에 맞는 반응형 ux/ui로 디자인하여 구축하였다.",
        "client":"SK DIGITAL CONSULTING",
        "category": "all, website",
        "category_tit": "website (responsive web)",
        "period": "2018.01",
        "size":"460,540",
        "backgroundColor":"#e51736",
        "link":""
    }, {
        "seq": "66",
        "type": "boxintxt",
        "title": "SK건설 공유 인프라",
        "notice":"직원들의 보다 편리한 정보공유를 위한 SK건설 공유 Infra 사이트를 리뉴얼하였다.",
        "pop_tit": "SK건설 공유 인프라",
        "pop_notice":"직원들의 보다 편리한 정보공유를 위한 SK건설 공유 Infra 사이트를 리뉴얼하였다.",
        "client":"SK건설",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2018.01",
        "size":"460,450",
        "backgroundColor":"#e51736",
        "link":""
    }, {
        "seq": "67",
        "type": "intxt",
        "title": "SK하이닉스 웹진 운영",
        "notice":"",
        "pop_tit": "SK하이닉스 웹진 운영",
        "pop_notice":"",
        "client":"SK하이닉스",
        "category": "all, website, management/promotion",
        "category_tit": "website, management/promotion",
        "period": "2018.10",
        "size":"220,300",
        "backgroundColor":"#c7cccf",
        "link":""
    }, {
        "seq": "68",
        "type": "outtxt",
        "title": "맥도날드 보안점검",
        "notice":"",
        "pop_tit": "맥도날드 보안점검",
        "pop_notice":"",
        "client":"맥도날드",
        "category": "all, website, web accessibility",
        "category_tit": "website, web accessibility",
        "period": "2018.02",
        "size":"220,280",
        "backgroundColor":"#d41f1f",
        "link":""
    }, {
        "seq": "69",
        "type": "intxt",
        "title": "이브아르 SNS운영",
        "title_color":"white",
        "notice":"2018년<br/>연간 계약 운영",
        "notice_color":"gray",
        "pop_tit": "이브아르 SNS운영",
        "pop_notice":"",
        "client":"LG화학",
        "category": "all, management/promotion",
        "category_tit": "국내sns, 해외sns",
        "period": "",
        "period_color":"white",
        "size":"460,180",
        "backgroundColor":"#f7c0ca",
        "link":""
    }, {
        "seq": "70",
        "type": "boxintxt",
        "title": "에어부산 UI/UX",
        "notice":"간편한 예약시스템을 위한 에어부산의 모바일웹,APP 리뉴얼 UI에 참여했습니다.",
        "pop_tit": "에어부산 UI/UX",
        "pop_notice":"간편한 예약시스템을 위한 에어부산의 모바일웹,APP 리뉴얼 UI에 참여했습니다.",
        "client":"에어부산",
        "category": "all, mobile, application",
        "category_tit": "mobile, application",
        "period": "2018.11",
        "size":"460,450",
        "backgroundColor":"#234791",
        "link":""
    }, {
        "seq": "71",
        "type": "outtxt",
        "title": "한국코퍼레이션 보안점검",
        "notice":"",
        "pop_tit": "한국코퍼레이션 보안점검",
        "pop_notice":"",
        "client":"한국코퍼레이션",
        "category": "all, website, web accessibility",
        "category_tit": "website, web accessibility",
        "period": "2018.10",
        "size":"220,400",
        "backgroundColor":"#2d5fa6",
        "link":""
    }, {
        "seq": "72",
        "type": "boxintxt",
        "title": "이브아르",
        "notice":"이브아르는 LG화학의 글로벌 필러 브랜드로 반응형 기반의 글로벌 홈페이지를 구축하였습니다.",
        "pop_tit": "이브아르",
        "pop_notice":"이브아르는 LG화학의 글로벌 필러 브랜드로 반응형 기반의 글로벌 홈페이지를 구축하였습니다.",
        "client":"LG화학",
        "category": "all, website",
        "category_tit": "website (responsive web)",
        "period": "2018.10",
        "size":"460,400",
        "backgroundColor":"#ea617b",
        "link":""
    }, {
        "seq": "73",
        "type": "outtxt",
        "title": "OB 보안점검",
        "notice":"",
        "pop_tit": "OB 보안점검",
        "pop_notice":"",
        "client":"OB맥주",
        "category": "all, website, web accessibility",
        "category_tit": "website, web accessibility",
        "period": "2018.11",
        "size":"220,380",
        "backgroundColor":"#002c76",
        "link":""
    }, {
        "seq": "74",
        "type": "boxintxt",
        "title": "LG연구소",
        "notice":"한국인 소아를 대상으로 의약품의 안정성을 평가하고 연구하기 위한 사이트를 구축하였습니다.",
        "pop_tit": "LG연구소",
        "pop_notice":"한국인 소아를 대상으로 의약품의 안정성을 평가하고<br/>연구하기 위한 사이트를 구축하였습니다.",
        "client":"LG연구소",
        "category": "all, website",
        "category_tit": "website",
        "period": "2019.01",
        "size":"460,460",
        "backgroundColor":"#0095a9",
        "link":""
    }, {
        "seq": "75",
        "type": "intxt",
        "title": "세이브더칠드런",
        "title_color":"white",
        "notice":"2019년<br/>연간 계약 운영",
        "notice_color":"gray",
        "pop_tit": "세이브더칠드런",
        "pop_notice":"2019년 연간 계약 운영",
        "client":"세이브더칠드런",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2019",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#c42834",
        "link":""
    }, {
        "seq": "76",
        "type": "outtxt",
        "title": "이브아르 SNS",
        "notice":"2019년 연간 계약 운영",
        "pop_tit": "이브아르 SNS",
        "pop_notice":"2019년 연간 계약 운영",
        "client":"이브아르",
        "category": "all, management/promotion",
        "category_tit": "국내sns, 해외sns",
        "period": "2019",
        "size":"220,430",
        "backgroundColor":"#ec617b",
        "link":""
    }, {
        "seq": "77",
        "type": "intxt",
        "title": "맥도날드",
        "title_color":"white",
        "notice":"2018년-2019년<br/>연간 계약 운영",
        "notice_color":"gray",
        "pop_tit": "맥도날드",
        "pop_notice":"2018년-2019년 연간 계약 운영",
        "client":"맥도날드",
        "category": "all, website, mobile, management/promotion",
        "category_tit": "website, mobile, management/promotion",
        "period": "2019",
        "period_color":"white",
        "size":"220,300",
        "backgroundColor":"#d41f1f",
        "link":""
    }, {
        "seq": "78",
        "type": "outtxt",
        "title": "엠마우스 알바워치 APP UI/UX",
        "notice":"",
        "pop_tit": "엠마우스 알바워치 APP UI/UX",
        "pop_notice":"",
        "client":"엠마우스",
        "category": "all, application",
        "category_tit": "application",
        "period": "2019.02",
        "size":"220,300",
        "backgroundColor":"#2487d8",
        "link":""
    }, {
        "seq": "79",
        "type": "boxintxt",
        "title": "아주대병원 APP UI/UX",
        "notice":"이용자들의 사용성과 편의성을 강화하고 아주대병원 이미지와 신뢰성을 높일 수 있는 디자인으로 개선되었습니다.",
        "pop_tit": "아주대병원 APP UI/UX",
        "pop_notice":"이용자들의 사용성과 편의성을 강화하고<br/>아주대병원 이미지와 신뢰성을 높일 수 있는 디자인으로 개선되었습니다.",
        "client":"아주대병원",
        "category": "all, application",
        "category_tit": "application",
        "period": "2019.03",
        "size":"460,440",
        "backgroundColor":"#4eaec6",
        "link":""
    }, {
        "seq": "80",
        "type": "boxintxt",
        "title": "LG화학 이브아르 국문",
        "notice":"이브아르 브랜드 가치를 높일 수 있는 사이트로 리뉴얼 되었습니다.",
        "pop_tit": "LG화학 이브아르 국문",
        "pop_notice":"이브아르 브랜드 가치를 높일 수 있는 사이트로 리뉴얼 되었습니다.",
        "client":"LG화학",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2019.07",
        "size":"460,450",
        "backgroundColor":"#ea617b",
        "link":""
    }, {
        "seq": "81",
        "type": "intxt",
        "title": "세이브더칠드런 긴급구호",
        "title_color":"white",
        "notice":"2019.08",
        "notice_color":"gray",
        "pop_tit": "세이브더칠드런 긴급구호",
        "pop_notice":"재난•재해에 대비하여 아이들을 구하기 위해 긴급구호아동기금을 후원할 수 있는 페이지를 제작하였습니다.",
        "client":"세이브더칠드런",
        "category": "all, website, mobile, management/promotion",
        "category_tit": "website, mobile, management/promotion",
        "period": "2019.08",
        "period_color":"white",
        "size":"460,180",
        "backgroundColor":"#c42834",
        "link":""
    }, {
        "seq": "82",
        "type": "intxt",
        "title": "세이브더칠드런 교육사이트",
        "notice":"",
        "pop_tit": "세이브더칠드런 교육사이트",
        "pop_notice":"",
        "client":"세이브더칠드런",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2019.08",
        "size":"220,300",
        "backgroundColor":"#c42834",
        "link":""
    }, {
        "seq": "83",
        "type": "outtxt",
        "title": "맥도날드 글로벌 빅맥 원정대 프로모션",
        "notice":"",
        "notice_color":"gray",
        "pop_tit": "맥도날드 글로벌<br/>빅맥 원정대 프로모션",
        "pop_notice":"30일간 매일 빅맥 퀴즈를 풀고 당첨 시 세계 주요 도시 30곳에 직접 가서 빅맥을 맛보고 여행도 할 수 있도록 제공하는 프로모션입니다.",
        "client":"맥도날드",
        "category": "all, management/promotion",
        "category_tit": "management/promotion",
        "period": "2019.07",
        "size":"220,400",
        "backgroundColor":"#d41f1f",
        "link":""
    }, {
        "seq": "84",
        "type": "boxintxt",
        "title": "LG화학 글로벌 이노베이션 센터",
        "notice":"LG화학이 보스턴에 글로벌 이노베이션 센터를 열고 글로벌 신약 개발을 진행하는 것에 대한 안내를 위해 제작된 사이트입니다.",
        "pop_tit": "LG화학 글로벌이노베이션 센터",
        "pop_notice":"LG화학이 미국 보스턴에 글로벌 이노베이션 센터를 열고 글로벌 신약 개발을 진행하는 것에 대한 안내를 위해 제작된 LG화학의 글로벌 이노베이션 센터의 대표 사이트입니다.",
        "client":"LG화학",
        "category": "all, website, mobile",
        "category_tit": "website (responsive web)",
        "period": "2019.09",
        "size":"460,500",
        "backgroundColor":"#c30036",
        "link":""
    }, {
        "seq": "85",
        "type": "outtxt",
        "title": "SK 지크 UI/UX",
        "notice":"",
        "notice_color":"gray",
        "pop_tit": "SK 지크 UI/UX",
        "pop_notice":"SK 지크 공식 홈페이지 WEB, MOBILE 퍼블리싱을 진행하였습니다.",
        "client":"SK지크",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2019.11",
        "size":"220,400",
        "backgroundColor":"#231f20",
        "link":""
    }, {
        "seq": "86",
        "type": "boxintxt",
        "title": "LG화학 유디APP",
        "notice":"유디는 성장호르몬 투여 아이를 대상으로 성장관리 서비스를 제공하기 위한 어플리케이션입니다.",
        "pop_tit": "LG화학 유디 APP",
        "pop_notice":"유디는 성장호르몬 투여 아이를 대상으로 올바른 성장호르몬의 사용 정보 제공과 체계적인 투여관리 그리고 지속적인 성장관리 서비스를 제공하기 위한 어플리케이션입니다.",
        "client":"LG화학",
        "category": "all, mobile, application",
        "category_tit": "mobile, application",
        "period": "2019.11",
        "size":"460,400",
        "backgroundColor":"#5a9216",
        "link":""
    }, {
        "seq": "87",
        "type": "intxt",
        "title": "SKT 제주 가로등 시스템 UI/UX",
        "notice":"",
        "pop_tit": "SKT 제주 가로등 시스템 UI/UX",
        "pop_notice":"",
        "client":"SKT",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2019.08",
        "size":"220,300",
        "backgroundColor":"#2cb1d0",
        "link":""
    }, {
        "seq": "88",
        "type": "boxintxt",
        "title": "네오팜샵 리뉴얼",
        "notice":"피부과학의 선도기업 네오팜 공식쇼핑몰인<br/>네오팜샵을 리뉴얼하였습니다.",
        "notice_color":"",
        "pop_tit": "네오팜샵 리뉴얼",
        "pop_notice":"",
        "client":"네오팜샵",
        "category": "all, website, mobile, application, shopping mall",
        "category_tit": "website, mobile, application, shopping mall",
        "period": "2020.01",
        "size":"460,390",
        "backgroundColor":"#77b1e1",
        "link":""
    }, {
        "seq": "89",
        "type": "outtxt",
        "title": "농협카드 올원페이 UI/UX",
        "notice":"",
        "notice_color":"gray",
        "pop_tit": "농협카드 올원페이 UI/UX",
        "pop_notice":"농협앱카드 올원페이의 WEB, MOBILE 디자인 리뉴얼을 진행하였습니다.",
        "client":"농협카드",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2019.12",
        "size":"220,300",
        "backgroundColor":"#1a4e8a",
        "link":""
    }, {
        "seq": "90",
        "type": "outtxt",
        "title": "세이브더칠드런",
        "notice":"",
        "notice_color":"gray",
        "pop_tit": "세이브더칠드런",
        "pop_notice":"2020년 연간 계약 운영",
        "client":"세이브더칠드런",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2020년 연간 계약 운영",
        "size":"220,400",
        "backgroundColor":"#c42834",
        "link":""
    }, {
        "seq": "91",
        "type": "boxintxt",
        "title": "LG MMA",
        "notice":"각종 산업용 소재로 사용되는 MMA를<br/>국산화하여 국제 경쟁력 강화에 이바지하는<br/>LG MMA의 사이트를 리뉴얼하였습니다.",
        "notice_color":"gray",
        "pop_tit": "LG MMA",
        "pop_notice":"각종 산업용 소재로 사용되는 MMA를 국산화하여<br/>국제 경쟁력 강화에 이바지하는 LG MMA의 사이트를 리뉴얼하였습니다.",
        "client":"LG MMA",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2020.08",
        "size":"460,460",
        "backgroundColor":"#5d6770",
        "link":""
    }, {
        "seq": "92",
        "type": "outtxt",
        "title": "LG화학 유디APP",
        "notice":"",
        "notice_color":"gray",
        "pop_tit": "LG화학 유디APP",
        "pop_notice":"2차, 3차 고도화 작업",
        "client":"LG화학",
        "category": "all, mobile, application",
        "category_tit": "mobile, application",
        "period": "2020.05 / 2021.09",
        "size":"220,300",
        "backgroundColor":"#5a9216",
        "link":""
    }, {
        "seq": "93",
        "type": "intxt",
        "title": "좋아서 하는 기념일",
        "title_color":"white",
        "notice":"",
        "notice_color":"gray",
        "pop_tit": "세이브더칠드런 좋아서 하는 기념일",
        "pop_notice":"2020년 연간 계약 운영",
        "client":"세이브더칠드런",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2020.05",
        "period_color":"gray",
        "size":"460,180",
        "backgroundColor":"#c42834",
        "link":""
    }, {
        "seq": "94",
        "type": "intxt",
        "title": "LG화학 글로벌 이노베이션",
        "title_color":"gray",
        "notice":"2020년 연간 운영",
        "notice_color":"gray2",
        "pop_tit": "LG화학 글로벌 이노베이션 센터",
        "pop_notice":"LG화학이 미국 보스턴에 글로벌 이노베이션 센터를 열고 글로벌 신약 개발을 진행하는 것에 대한 안내를 위해 제작된 LG화학의 글로벌 이노베이션 센터의 대표 사이트입니다.",
        "client":"LG화학",
        "category": "all, website (responsive web)",
        "category_tit": "website (responsive web)",
        "period": "2019.09",
        "period_color":"none",
        "size":"220,300",
        "backgroundColor":"#c42834",
        "link":""
    }, {
        "seq": "95",
        "type": "intxt",
        "title": "유니세프 온라인 필드트립 프로모션",
        "title_color":"white",
        "notice":"",
        "pop_tit": "유니세프 온라인 필드트립 프로모션",
        "pop_notice":"",
        "client":"유니세프한국위원회",
        "category": "all, mobile, management/promotion",
        "category_tit": "mobile, management/promotion",
        "period": "2020.11",
        "period_color":"gray",
        "size":"220,300",
        "backgroundColor":"#3162af",
        "link":""
    }, {
        "seq": "96",
        "type": "boxintxt",
        "title": "유니세트 후원자 온라인 캠페인",
        "title_color":"blk",
        "notice":"",
        "pop_tit": "유니세트 후원자 온라인 캠페인",
        "pop_notice":"",
        "client":"유니세프한국위원회",
        "category": "all, website, mobile, management/promotion",
        "category_tit": "website, mobile, management/promotion",
        "period": "2021.01",
        "size":"460,460",
        "backgroundColor":"#3162af",
        "link":""
    }, {
        "seq": "97",
        "type": "intxt",
        "title": "LG화학 글로벌<br/>이노베이션",
        "title_color":"blk",
        "notice":"2021년 연간 운영",
        "notice_color":"gray2",
        "pop_tit": "LG화학 글로벌 이노베이션 센터",
        "pop_notice":"2021년 연간 운영",
        "client":"LG화학",
        "category": "all, website",
        "category_tit": "website (responsive web)",
        "period": "2021.01",
        "period_color":"none",
        "size":"220,300",
        "backgroundColor":"#c30036",
        "link":""
    }, {
        "seq": "98",
        "type": "intxt",
        "title": "유니세프<br/>한국위원회",
        "title_color":"blk",
        "notice":"유니세프 유산기부<br/>캠페인 1차, 2차",
        "notice_color":"gray2",
        "pop_tit": "유니세프 유산기부 캠페인 1차, 2차",
        "pop_notice":"유니세프 유산기부 캠페인 1차, 2차",
        "client":"유니세프한국위원회",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2021.01 / 2021.10",
        "period_color":"none",
        "size":"220,300",
        "backgroundColor":"#0971ad",
        "link":""
    }, {
        "seq": "99",
        "type": "boxintxt",
        "title": "ITECH",
        "notice":"ITECH 산업기술국책과제 3년 수주<br/>&nbsp",
        "notice_color":"gray",
        "pop_tit": "ITECH 산업기술국책과제 3년 수주",
        "pop_notice":"주관기관 : 산업통상자원부<br/>전담기관 : 한국산업기술평가관리원<br/>과제명 : 디자인혁신역량강화사업<br/>수행기간 : 2021년~2023년",
        "client":"산업통상자원부",
        "category": "all, application",
        "category_tit": "application",
        "period": "2021~2023",
        "size":"460,460",
        "backgroundColor":"#cd6917",
        "link":""
    }, {
        "seq": "100",
        "type": "outtxt",
        "title": "LX MMA",
        "notice":"",
        "notice_color":"gray",
        "pop_tit": "LX MMA",
        "pop_notice":"",
        "client":"(주)LX MMA",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2021.01",
        "size":"220,300",
        "backgroundColor":"#a72b2b",
        "link":""
    }, {
        "seq": "101",
        "type": "intxt",
        "title": "LG화학 유디APP",
        "title_color":"white",
        "notice":"블루투스 기능 추가",
        "notice_color":"gray",
        "pop_tit": "LG화학 유디APP",
        "pop_notice":"블루투스 기능 추가",
        "client":"LG화학",
        "category": "all, mobile",
        "category_tit": "mobile, application",
        "period": "2021.12",
        "period_color":"gray",
        "size":"220,300",
        "backgroundColor":"#5a9216",
        "link":""
    }, {
        "seq": "102",
        "type": "outtxt",
        "title": "차량정산시스템",
        "notice":"",
        "pop_tit": "차량정산시스템",
        "pop_notice":"",
        "client":"주식회사 차지비",
        "category": "all, website",
        "category_tit": "website",
        "period": "2021.12",
        "size":"220,400",
        "backgroundColor":"#525252",
        "link":""
    }, {
        "seq": "103",
        "type": "intxt",
        "title": "LG화학 글로벌<br/>이노베이션",
        "title_color":"blk",
        "notice":"2022년 연간 운영",
        "notice_color":"gray2",
        "pop_tit": "LG화학 글로벌 이노베이션 센터",
        "pop_notice":"2022년 연간 운영",
        "client":"LG화학",
        "category": "all, website",
        "category_tit": "website (responsive web)",
        "period": "2022.01",
        "period_color":"none",
        "size":"220,300",
        "backgroundColor":"#c30036",
        "link":""
    }, {
        "seq": "104",
        "type": "boxintxt",
        "title": "SK D&D",
        "notice":"&nbsp<br/>&nbsp<br/>",
        "pop_tit": "SK D&D",
        "pop_notice":"",
        "client":"SK D&D(주)",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2022.01",
        "size":"460,444",
        "backgroundColor":"#ed7508",
        "link":""
    }, {
        "seq": "105",
        "type": "intxt",
        "title": "유니세프 한국위원회",
        "title_color":"white",
        "notice":"2022년<br/> 연간 운영",
        "notice_color":"gray",
        "pop_tit": "유니세프 한국위원회",
        "pop_notice":"2022년 연간 운영",
        "client":"유니세프한국위원회",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2022.02",
        "period_color":"none",
        "size":"220,300",
        "backgroundColor":"#3162af",
        "link":""
    }, {
        "seq": "106",
        "type": "boxintxt",
        "title": "SK 에코엔지니어링",
        "notice":"&nbsp<br/>&nbsp<br/>",
        "pop_tit": "SK 에코엔지니어링",
        "pop_notice":"",
        "client":"SK에코플랜트",
        "category": "all, website, mobile",
        "category_tit": "website, mobile",
        "period": "2022.02",
        "size":"460,444",
        "backgroundColor":"#009a92",
        "link":""
    }, {
        "seq": "107",
        "type": "intxt",
        "title": "SK<br/> 환경시설관리<br/> 주식회사",
        "title_color":"white",
        "notice":"",
        "notice_color":"gray",
        "pop_tit": "SK 환경시설관리 주식회사",
        "pop_notice":"",
        "client":"환경시설관리(주)",
        "category": "all, website",
        "category_tit": "website",
        "period": "2022.06",
        "period_color":"gray",
        "size":"220,300",
        "backgroundColor":"#6b8240",
        "link":""
    }
]
}
